get http://localhost:3001/api/points

###

POST http://localhost:3001/api/points
Content-Type: application/json

{
    "type": "event",
    "content": "Battle rap",
    "longitude": -79.380520,
    "latitude": 43.658487
}

###

get http://localhost:3001/api/points/5de034adc665846030b938fa